# Demo CI workflow with TcUnit-Runner
name: TcUnit-Runner
 
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
 
jobs:
 
  tcunit_runner:
 
    # a self hosted runner, i.e. VM with tag 'tcunit'
    runs-on: [ self-hosted ]
 
    steps:
 
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Run TcUnit-Runner
        shell: cmd
        # Start TcUnit-Runner with a timeout of 5 min
        # run: '"C:\Program Files (x86)\TcUnit-Runner\LaunchTcUnit.bat" -U 5 -a 5.143.131.226.1.1'
        run: '"C:\Users\maart\OneDrive\Documents\Desktop\LaunchTcUnit.lnk" -U 5 -a 5.143.131.226.1.1'
